// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwyKTmve9LulK246dR0KqecK0kX51hTdc',
    appId: '1:572363600328:web:848a5cb1100bc8b685d0fd',
    messagingSenderId: '572363600328',
    projectId: 'toko-electronic',
    authDomain: 'toko-electronic.firebaseapp.com',
    storageBucket: 'toko-electronic.firebasestorage.app',
    measurementId: 'G-L86CC8FMQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpMPCEEL3_8cQizAG9f6t2J2H34mbFTQ',
    appId: '1:572363600328:android:d52968632e59869785d0fd',
    messagingSenderId: '572363600328',
    projectId: 'toko-electronic',
    storageBucket: 'toko-electronic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9s2TDkDUh3of_s4kHnNyfLtZsu2GTCo',
    appId: '1:572363600328:ios:479ad7ff9ee1fd5185d0fd',
    messagingSenderId: '572363600328',
    projectId: 'toko-electronic',
    storageBucket: 'toko-electronic.firebasestorage.app',
    iosBundleId: 'com.example.tokoElectronik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9s2TDkDUh3of_s4kHnNyfLtZsu2GTCo',
    appId: '1:572363600328:ios:479ad7ff9ee1fd5185d0fd',
    messagingSenderId: '572363600328',
    projectId: 'toko-electronic',
    storageBucket: 'toko-electronic.firebasestorage.app',
    iosBundleId: 'com.example.tokoElectronik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwyKTmve9LulK246dR0KqecK0kX51hTdc',
    appId: '1:572363600328:web:f9b8ab29a2e27b4685d0fd',
    messagingSenderId: '572363600328',
    projectId: 'toko-electronic',
    authDomain: 'toko-electronic.firebaseapp.com',
    storageBucket: 'toko-electronic.firebasestorage.app',
    measurementId: 'G-V4Z9BCNV5D',
  );

}